# Generated by Django 5.0.2 on 2024-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_created_by_task_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "category")},
        ),
    ]
